name: Lock Threads

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - name: Lock Threads
        uses: dessant/lock-threads@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          issue-lock-inactive-days: '30'
          pr-lock-inactive-days: '30'
